fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref: "9.1.0"
    ruby_plugin_helper:
      repo: "puppetlabs/ruby_plugin_helper"
      ref: "0.2.0"
    ruby_task_helper:
      repo: "puppetlabs/ruby_task_helper"
      ref: "0.6.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.4.0"
    rvm:
      repo: "puppetlabs/terraform"
      ref: "0.7.0"
    yumrepo:
      repo: "puppetlabs-yumrepo_core"
      ref: "2.0.0"
  repositories:
    puppet_agent:
      repo: https://github.com/puppetlabs/puppetlabs-puppet_agent.git
      ref: v4.13.0
    facts: https://github.com/puppetlabs/puppetlabs-facts.git
    # provision: https://github.com/puppetlabs/provision.git
